version: '3'

services:
  zk:
    image: confluentinc/cp-zookeeper
    container_name: zk
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zk
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  graphite:
    image: nickstenning/graphite
    container_name: graphite
    ports:
      - "80:80"
      - "2003:2003"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.1.0
    container_name: schema-registry
    depends_on:
      - kafka
      - zk
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zk:2181
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - "8081:8081"

  management:
    image: hermes-management
    container_name: management
    ports:
      - "8090:8090"
    depends_on:
      - zk
      - kafka
      - graphite

  frontend:
    image: hermes-frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - zk
      - kafka
      - graphite

  consumer:
    image: hermes-consumers
    container_name: consumer
    depends_on:
      - zk
      - kafka
      - graphite

  subscriber:
    image: hermes-subscriber
    container_name: subscriber

