FROM alpine

RUN apk add openssl
RUN mkdir -p /etc/ssl/private
RUN mkdir -p /etc/ssl/certs
RUN openssl req \
    -x509 \
    -nodes \
    -days 365 \
    -subj "/C=CA/ST=QC/O=Company, Inc./CN=subscriber" \
    -addext "subjectAltName=DNS:subscriber" \
    -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt

