zookeeper:
  enabled: false


storage:
  pathPrefix: /run/hermes
  clusters:
    -
      datacenter: dc
      clusterName: zk
      connectionString: zk:2181

kafka:
  clusters:
    -
      datacenter: dc
      clusterName: primary
      connectionString: zk:2181
      connectionTimeout: 3000
      bootstrapKafkaServer: kafka:9092

spring:
  jersey:
    type: servlet
  mvc:
    servlet:
      path: /status

server:
  port: 8090

management:
  endpoints:
    web:
      base-path: /
  rest-template:
    connect-timeout: 2000
    read-timeout: 2000
  server:
    servlet:
      context-path: /
  health:
    periodSeconds: 30
    enabled: true
  consumer-groups:
    create-manually: true

audit.enabled: false

topicOwnerCache:
  refreshRateInSeconds: 300 # 5 minutes

subscriptionOwnerCache:
  refreshRateInSeconds: 300

schema.repository:
  serverUrl: http://schema-registry:8081
  validationEnabled: true

